########################################################
################ COMING AND GOING ######################
########################################################

- id: location_change
  alias: GPS Location Changed
  trigger:
    - platform: state
      entity_id: device_tracker.7ac50169
    - platform: state
      entity_id: device_tracker.lgd801c8e9841a
  condition:
    - condition: template
      value_template: '{{trigger.to_state.state != trigger.from_state.state}}'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: '{{"input_select.christys_location" if trigger.entity_id == "device_tracker.lgd801c8e9841a" else "input_select.seths_location"}}'
        option: >
          {%-if trigger.to_state.state == 'home'-%}
            {%-if (trigger.entity_id == 'device_tracker.lgd801c8e9841a' and states.input_select.christys_location.state == 'just_left') or (trigger.entity_id == 'device_tracker.7ac50169' and states.input_select.seths_location.state == 'just_left')-%}
              home
            {%-else-%}
              just_arrived
            {%-endif-%}
          {%-elif trigger.to_state.state == 'not_home' and trigger.from_state.state == 'home'%}
            just_left
          {%-else-%}
            {{trigger.to_state.state}}
          {%-endif-%}

- id: location_change_2
  alias: Just Left/Arived finished
  trigger:
    - platform: state
      entity_id: input_select.seths_location
      to: 'just_left'
      for:
        minutes: 5
    - platform: state
      entity_id: input_select.seths_location
      to: 'just_arrived'
      for:
        minutes: 5
    - platform: state
      entity_id: input_select.christys_location
      to: 'just_left'
      for:
        minutes: 5
    - platform: state
      entity_id: input_select.christys_location
      to: 'just_arrived'
      for:
        minutes: 5
  action:
    - service: input_select.select_option
      data_template:
        entity_id: '{{"input_select.christys_location" if trigger.entity_id == "input_select.christys_location" else "input_select.seths_location"}}'
        option: '{{"not_home" if trigger.to_state.state == "just_left" else "home"}}'
    
- id: cancel_resume_ecobee_clicked
  alias: Cancel Resume Ecobee Notification Clicked
  trigger:
  - platform: event
    event_type: html5_notification.clicked
    event_data:
      action: cancel_ecobee_home
  action:
  - service: climate.set_hold_mode
    data:
      entity_id: "climate.bigbee"
      hold_mode: "away"

########################################################
################     MOTION      #######################
########################################################

- id: input_select_kitchen_motion_changed
  alias: Input Select Kitchen Motion Changed
  trigger:
    - platform: state
      entity_id: input_select.kitchen_motion
  action:
    - service: scene.turn_on
      data_template:
        entity_id: 'scene.kitchen_{{trigger.to_state.state}}'

- id: input_select_dining_room_motion_changed
  alias: Input Select Dining Room Motion Changed
  trigger:
    - platform: state
      entity_id: input_select.dining_room_motion
  action:
    - service: scene.turn_on
      data_template:
        entity_id: 'scene.dining_room_{{trigger.to_state.state}}'

- id: input_select_living_room_motion_changed
  alias: Input Select Living Room Motion Changed
  trigger:
    - platform: state
      entity_id: input_select.living_room_motion
  action:
    - service: scene.turn_on
      data_template:
        entity_id: 'scene.living_room_{{trigger.to_state.state}}'

########################################################
################  NOTIFICATIONS  #######################
########################################################
- id: light_left_on
  alias: Light Left On
  trigger:
  - platform: state
    entity_id: switch.wemo_switch_1
    to: "on"
    for: 01:00:00
  - platform: state
    entity_id: switch.wemo_switch_2
    to: "on"
    for: 01:00:00
  - platform: state
    entity_id: switch.front_porch
    to: "on"
    for: 00:30:00
  - platform: state
    entity_id: switch.garage
    to: "on"
    for: 01:00:00
  - platform: state
    entity_id: switch.back_porch_fan
    to: "on"
    for: 01:00:00
  action:
  - service: notify.html5
    data:
      target:
      - "seths_one_plus_3t"
      - "christys_lg_g2"
    data_template:
      title: 'Light Left On'
      message: >
        {{trigger.to_state.attributes.friendly_name}} was left on.
      data:
        tag: >
          {{trigger.entity_id}}_left_on
        my_id: >
          {{trigger.entity_id}}
        actions:
        - action: "turn_off_switch"
          title: "Turn Off"
          icon: "/local/lightbulb-on.png"

- id: turn_off_light_notification_clicked
  alias: Turn Off Light Notification Clicked
  trigger:
  - platform: event
    event_type: html5_notification.clicked
    event_data:
      action: turn_off_switch
  action:
  - service: homeassistant.turn_off
    data_template:
      entity_id: >
        {{trigger.event.data.data['my_id']}}

########################################################
################ ECOBEE/CLIMATE  #######################
########################################################

#- id: select_input_ecobee
#  alias: Set Input Select if ecobee operation mode changes
#  trigger:
#  - platform: state
#    entity_id: climate.bigbee
#  action:
#    service: input_select.select_option
#    data_template:
#      entity_id: input_select.ecobee_operation_mode
#      option: >
#        {{ states.climate.bigbee.attributes.operation_mode or NA }}

#- id: set_ecobee_operation
#  alias: Set Ecobee operation mode from input_select
#  trigger:
#    platform: state
#    entity_id: input_select.ecobee_operation_mode
#  action:
#  - service: climate.set_operation_mode
#    data_template:
#      entity_id: climate.bigbee
#      operation_mode: "{{trigger.to_state.state}}"

#- id: set_ecobee_hold
#  alias: Set Input Select if ecobee hold mode changes
#  trigger:
#  - platform: state
#    entity_id: climate.ecobee
#  action:
#    service: input_select.select_option
#    data_template:
#      entity_id: input_select.ecobee_hold_mode
#      option: >-
#        {{states.climate.bigbee.attributes.hold_mode or "none" }}

#- id: set_ecobee_hold_from_select
#  alias: Set Ecobee Hold from input_select
#  trigger:
#    platform: state
#    entity_id: input_select.ecobee_hold_mode
#  action:
#  - service: climate.set_hold_mode
#    data_template:
#      entity_id: climate.bigbee
#      hold_mode: "{{trigger.to_state.state}}"

#- id: warmer_tomorrow
#  alias: Warmer Tomorrow
#  condition:
#  - condition: state
#    entity_id: sensor.ecobee_operation_mode
#    state: "heat"
#  - condition: numeric_state
#    entity_id: sensor.dark_sky_daily_high_temperature_1
#    above: 63
#  trigger:
#  - platform: time
#    at: '22:00:00'
#  action:
#    service: notify.html5
#    data_template:
#      message: "High tomorrow is {{states('sensor.dark_sky_daily_high_temperature_1')}}{{sensor.dark_sky_daily_high_temperature_1.attributes.unit_of_measurement}}, turning off heat in the morning"
#      data:
#        tag: "ecobee_automate"
#        mode: "off"
#        actions:
#        - action: change_ecobee_operation_mode
#          title: "Turn off heater now"

#- id: warm_today
#  alias: Warm Today
#  condition:
#  - condition: state
#    entity_id: sensor.ecobee_operation_mode
#    state: "heat"
#  - condition: numeric_state
#    entity_id: sensor.dark_sky_daily_high_temperature
#    above: 63
#  trigger:
#  - platform: time
#    at: '07:30:00'
#  action:
#  - service: input_select.select_option
#    data:
#      entity_id: input_select.ecobee
#      option: "off"
#  - service: notify.html5
#    data_template:
#      message: "High today is {{states('sensor.dark_sky_daily_high_temperature')}}{{sensor.dark_sky_daily_high_temperature.attributes.unit_of_measurement}}, turning off heat"
#      data:
#        tag: "ecobee_automate"
#        mode: "heat"
#        actions:
#        - action: change_ecobee_operation_mode
#          title: "Turn heat back on"
   
#- id: cold_tomorrow
#  alias: Cold Tomorrow
#  condition:
#  - condition: state
#    entity_id: sensor.ecobee_operation_mode
#    state: "off"
#  - condition: numeric_state
#    entity_id: sensor.dark_sky_daily_high_temperature_1
#    below: 63
#  trigger:
#  - platform: time
#    at: '22:00:00'
#  action:
#    service: notify.html5
#    data_template:
#      message: "High tomorrow is {{states('sensor.dark_sky_daily_high_temperature_1')}}{{sensor.dark_sky_daily_high_temperature_1.attributes.unit_of_measurement}}."
#      data:
#        tag: "ecobee_automate"
#        mode: "heat"
#        actions:
#        - action: change_ecobee_operation_mode
#          title: Turn on heater

#- id: cooler_tomorrow
#  alias: Cooler Tomorrow
#  condition:
#  - condition: state
#    entity_id: sensor.ecobee_operation_mode
#    state: "cool"
#  - condition: numeric_state
#    entity_id: sensor.dark_sky_daily_high_temperature_1
#    below: 87.5
#  trigger:
#  - platform: time
#    at: '22:00:00'
#  action:
#    service: notify.html5
#    data_template:
#      message: "High tomorrow is {{states('sensor.dark_sky_daily_high_temperature_1')}}{{sensor.dark_sky_daily_high_temperature_1.attributes.unit_of_measurement}}, turning off A/C in the morning"
#      data:
#        tag: "ecobee_automate"
#        mode: "off"
#        actions:
#        - action: change_ecobee_operation_mode
#          title: "Turn off A/C now"

#- id: cooler_today
#  alias: Cooler Today
#  condition:
#  - condition: state
#    entity_id: sensor.ecobee_operation_mode
#    state: "cool"
#  - condition: numeric_state
#    entity_id: sensor.dark_sky_daily_high_temperature
#    below: 87.5
#  trigger:
#  - platform: time
#    at: '07:30:00'
#  action:
#  - service: input_select.select_option
#    data:
#      entity_id: input_select.ecobee
#      option: "off"
#  - service: notify.html5
#    data_template:
#      message: "High today is {{states('sensor.dark_sky_daily_high_temperature')}}{{sensor.dark_sky_daily_high_temperature.attributes.unit_of_measurement}}, turning off A/C"
#      data:
#        tag: "ecobee_automate"
#        mode: "cool"
#        actions:
#        - action: change_ecobee_operation_mode
#          title: "Turn A/C back on"
   
#- id: hot_tomorrow
#  alias: Hot Tomorrow
#  condition:
#  - condition: state
#    entity_id: sensor.ecobee_operation_mode
#    state: "off"
#  - condition: numeric_state
#    entity_id: sensor.dark_sky_daily_high_temperature_1
#    above: 87.5
#  trigger:
#  - platform: time
#    at: '22:00:00'
#  action:
#    service: notify.html5
#    data_template:
#      message: "High tomorrow is {{states('sensor.dark_sky_daily_high_temperature_1')}}{{sensor.dark_sky_daily_high_temperature_1.attributes.unit_of_measurement}}."
#      data:
#        tag: "ecobee_automate"
#        mode: "cool"
#        actions:
#        - action: change_ecobee_operation_mode
#          title: Turn on A/C

- id: hvac_notification_clicked
  alias: Turn on/off HVAC Notification Clicked
  trigger:
  - platform: event
    event_type: html5_notification.clicked
    event_data:
      action: change_ecobee_operation_mode
  action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.ecobee
      option: >
        {{trigger.event.data.data['mode']}}
 
