########################################################
################ COMING AND GOING ######################
########################################################
- alias: Christy Got Home While Seth Away
  condition:
  - condition: state
    entity_id: device_tracker.sethsphone
    state: 'not_home'
  trigger:
  - platform: state
    entity_id: device_tracker.christysphone
    from: 'not_home'
    to: 'home'
  action:
  - delay: '00:01:00'
  - condition: state
    entity_id: device_tracker.sethsphone
    state: 'not_home'      
  - service: notify.html5
    data:
      target: "seths_one_plus_3t"
      message: "Christy is now home."
      data:
        tag: "christy_is_home"

- alias: Seth left work
  condition:
  - condition: time
    after: '15:30:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  trigger: 
    platform: state
    entity_id: device_tracker.sethsphone
    from: "work"
    to: "not_home"
  action:
    service: notify.html5
    data:
      target: "christys_lg_g2"
      message: "Seth Left Work."
      data:
        tag: "seth_left_work"
      
- alias: Someone Got Home, turn on the lights
  condition:
  - condition: sun
    after: sunset
  - condition: state
    entity_id: switch.front_porch
    state: "off"
  trigger:
  - platform: state
    entity_id: device_tracker.sethsphone
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: device_tracker.christysphone
    from: 'not_home'
    to: 'home'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_front_porch

- alias: Someone left, turn off the porch light
  condition:
  - condition: state
    entity_id: switch.front_porch
    state: "on"
  - condition: template
    value_template: "{{ (as_timestamp(now()) - as_timestamp(trigger.to_state.last_changed)) < 900 }}"
  trigger:
  - platform: state
    entity_id: device_tracker.sethsphone
    from: 'home'
    to: 'not_home'
  - platform: state
    entity_id: device_tracker.christysphone
    from: 'home'
    to: 'not_home'
  action:
    service: homeassistant.turn_off
    entity_id: switch.front_porch

- alias: Everyone left, set away mode, turn off devices
  trigger:
  - platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  action:
  - service: switch.turn_on
    entity_id: switch.ecobee_away_mode
  - service: homeassistant.turn_on
    entity_id: script.turn_off_all
    
- alias: Someone got home, resume Ecobee
  trigger:
  - platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  action:
  - service: homeassistant.turn_on
    entity_id: script.ecobee_resume_program

## TODO: Change to "home & hold" once implemented
- alias: Heading Home, resume Ecobee
  trigger:
  - platform: state
    entity_id: device_tracker.sethsphone
    to: "not_home"
  - platform: state
    entity_id: device_tracker.christysphone
    to: "not_home"
  condition:
  - condition: template
    value_template: >
      {{ trigger.from_state.state != "home" }}
  - condition: template
    value_template: >
      {{ as_timestamp(now()) - as_timestamp(trigger.from_state.last_changed) > 2400 }}
  action:
  - service: homeassistant.turn_on
    entity_id: script.ecobee_resume_program
    
- alias: Bedtime
  trigger:
  - platform: time
    hours: 00
    minutes: 30
    seconds: 00
  action:
  - service: homeassistant.turn_on
    entity_id: script.turn_off_all
    
########################################################
################     MOTION      #######################
########################################################

- alias: Family Room Occupied
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: sensor.family_room
      state: "PowerOff"
  trigger:
  - platform: state
    entity_id: sensor.seths_internal_location
    state: 'family room'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.wemo_switch_1
- alias: Family Room Empty
  condition:
    condition: template
    value_template: >
      {{ as_timestamp(now()) - as_timestamp(trigger.from_state.last_changed) < 600 }}
  trigger:
  - platform: state
    entity_id: sensor.seths_internal_location
    from: 'family room'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.wemo_switch_1

# Occupancy at night, vacancy during the day
- alias: Kitchen Table Motion
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: switch.kitchen_table
      state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_table_motion
    state: 'on'
  action:
  - service: script.light_timer
    data:
      time: '00:05:00'
      entity: 'switch.kitchen_table'


########################################################
################  NOTIFICATIONS  #######################
########################################################
- alias: Light Left On
  trigger:
  - platform: state
    entity_id: switch.wemo_switch_1
    to: "on"
    for: 01:00:00
  - platform: state
    entity_id: switch.wemo_switch_2
    to: "on"
    for: 01:00:00
  - platform: state
    entity_id: switch.front_porch
    to: "on"
    for: 00:30:00
  action:
  - service: notify.html5
    data:
      target:
      - "seths_one_plus_3t"
      - "christys_lg_g2"
    data_template:
      message: >
        {{trigger.to_state.attributes.friendly_name}} was left on.
      data:
        tag: >
          {{trigger.entity_id}}_left_on
        my_id: >
          {{trigger.entity_id}}
        actions:
        - action: "turn_off_switch"
          title: "Turn Off"
          icon: "/local/lightbulb-on.png"
- alias: Turn Off Light Notification Clicked
  trigger:
  - platform: event
    event_type: html5_notification.clicked
    event_data:
      action: turn_off_switch
  action:
  - service: homeassistant.turn_off
    data_template:
      entity_id: >
        {{trigger.event.data.data['my_id']}}


- alias: Power Event Occured
  trigger:
  - platform: numeric_state
    entity_id: sensor.ups_battery
    below: 100
  action:
  - service: notify.html5
    data:
      target: "seths_one_plus_3t"
      message: "Power Event Occured"

- alias: Garage Door Left Open
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_door
    state: "on"
    for: 01:00:00
  action:
  - service: notify.html5
    data:
      message: "Garage Door is Open"
      

########################################################
################ ECOBEE/CLIMATE  #######################
########################################################

- alias: Set Input Select if ecobee operation mode changes
  trigger:
  - platform: state
    entity_id: climate.bigbee
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.ecobee_operation_mode
      option: >
        {{ states.climate.bigbee.attributes.operation_mode or NA }}

- alias: Set Ecobee operation mode from input_select
  trigger:
    platform: state
    entity_id: input_select.ecobee_operation_mode
  action:
  - service: climate.set_operation_mode
    data_template:
      entity_id: climate.bigbee
      operation_mode: "{{trigger.to_state.state}}"

- alias: Set Input Select if ecobee hold mode changes
  trigger:
  - platform: state
    entity_id: climate.ecobee
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.ecobee_hold_mode
      option: >-
        {{states.climate.bigbee.attributes.hold_mode or "none" }}

- alias: Set Ecobee Hold from input_select
  trigger:
    platform: state
    entity_id: input_select.ecobee_hold_mode
  action:
  - service: climate.set_hold_mode
    data_template:
      entity_id: climate.bigbee
      hold_mode: "{{trigger.to_state.state}}"

- alias: Warmer Tomorrow
  condition:
  - condition: state
    entity_id: sensor.ecobee_operation_mode
    state: "heat"
  - condition: numeric_state
    entity_id: sensor.dark_sky_daily_high_temperature_1
    above: 63
  trigger:
  - platform: time
    after: '22:00:00'
  action:
    service: notify.html5
    data_template:
      message: "High tomorrow is {{states('sensor.dark_sky_daily_high_temperature_1')}}{{sensor.dark_sky_daily_high_temperature_1.attributes.unit_of_measurement}}, turning off heat in the morning"
    data:
      tag: "ecobee_automate"
      mode: "off"
      actions:
      - action: change_ecobee_operation_mode
        title: "Turn off heater now"

- alias: Warm Today
  condition:
  - condition: state
    entity_id: sensor.ecobee_operation_mode
    state: "heat"
  - condition: numeric_state
    entity_id: sensor.dark_sky_daily_high_temperature
    above: 63
  trigger:
  - platform: time
    after: '07:30:00'
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.ecobee
      option: "off"
  - service: notify.html5
    data_template:
      message: "High today is {{states('sensor.dark_sky_daily_high_temperature')}}{{sensor.dark_sky_daily_high_temperature.attributes.unit_of_measurement}}, turning off heat"
    data:
      tag: "ecobee_automate"
      mode: "heat"
      actions:
      - action: change_ecobee_operation_mode
        title: "Turn heat back on"
   
- alias: Cold Tomorrow
  condition:
  - condition: state
    entity_id: sensor.ecobee_operation_mode
    state: "off"
  - condition: numeric_state
    entity_id: sensor.dark_sky_daily_high_temperature_1
    below: 63
  trigger:
  - platform: time
    after: '22:00:00'
  action:
    service: notify.html5
    data_template:
      message: "High tomorrow is {{states('sensor.dark_sky_daily_high_temperature_1')}}{{sensor.dark_sky_daily_high_temperature_1.attributes.unit_of_measurement}}."
    data:
      tag: "ecobee_automate"
      mode: "heat"
      actions:
      - action: change_ecobee_operation_mode
        title: Turn on heater

- alias: Cooler Tomorrow
  condition:
  - condition: state
    entity_id: sensor.ecobee_operation_mode
    state: "cool"
  - condition: numeric_state
    entity_id: sensor.dark_sky_daily_high_temperature_1
    below: 87.5
  trigger:
  - platform: time
    after: '22:00:00'
  action:
    service: notify.html5
    data_template:
      message: "High tomorrow is {{states('sensor.dark_sky_daily_high_temperature_1')}}{{sensor.dark_sky_daily_high_temperature_1.attributes.unit_of_measurement}}, turning off A/C in the morning"
    data:
      tag: "ecobee_automate"
      mode: "off"
      actions:
      - action: change_ecobee_operation_mode
        title: "Turn off A/C now"

- alias: Cooler Today
  condition:
  - condition: state
    entity_id: sensor.ecobee_operation_mode
    state: "cool"
  - condition: numeric_state
    entity_id: sensor.dark_sky_daily_high_temperature
    below: 87.5
  trigger:
  - platform: time
    after: '07:30:00'
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.ecobee
      option: "off"
  - service: notify.html5
    data_template:
      message: "High today is {{states('sensor.dark_sky_daily_high_temperature')}}{{sensor.dark_sky_daily_high_temperature.attributes.unit_of_measurement}}, turning off A/C"
    data:
      tag: "ecobee_automate"
      mode: "cool"
      actions:
      - action: change_ecobee_operation_mode
        title: "Turn A/C back on"
   
- alias: Hot Tomorrow
  condition:
  - condition: state
    entity_id: sensor.ecobee_operation_mode
    state: "off"
  - condition: numeric_state
    entity_id: sensor.dark_sky_daily_high_temperature_1
    above: 87.5
  trigger:
  - platform: time
    after: '22:00:00'
  action:
    service: notify.html5
    data_template:
      message: "High tomorrow is {{states('sensor.dark_sky_daily_high_temperature_1')}}{{sensor.dark_sky_daily_high_temperature_1.attributes.unit_of_measurement}}."
    data:
      tag: "ecobee_automate"
      mode: "cool"
      actions:
      - action: change_ecobee_operation_mode
        title: Turn on A/C

- alias: Turn on/off HVAC Notification Clicked
  trigger:
  - platform: event
    event_type: html5_notification.clicked
    event_data:
      action: change_ecobee_operation_mode
  action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.ecobee
      option: >
        {{trigger.event.data.data['mode']}}
 
########################################################
################ HARMONY REMOTE  #######################
########################################################

- alias: Set Input Select when Harmony Changes
  trigger:
  - platform: state
    entity_id: sensor.family_room
  - platform: event
    event_type: homeassistant_start
  action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.harmony_activity
      option: >
        {{ states.sensor.family_room.state }}

- alias: Start Harmony Acitivity from input_select
  trigger:
    platform: state
    entity_id: input_select.harmony_activity
  action:
  - service: remote.turn_on
    data_template:
      entity_id: remote.familyroom
      activity: "{{trigger.to_state.state}}"

- alias: Start PC when Watch PC selected
  trigger:
  - platform: state
    entity_id: input_select.harmony_activity
    state: "Watch PC"
  - platform: state
    entity_id: sensor.family_room
    state: "Watch PC"
  action:
  - service: homeassistant.turn_on
    entity_id: switch.htpc

- alias: Shutdown PC when Watch PC deselected
  trigger:
  - platform: state
    entity_id: input_select.harmony_activity
    from: "Watch PC"
  - platform: state
    entity_id: sensor.family_room
    from: "Watch PC"
  action:
  - service: homeassistant.turn_off
    entity_id: switch.htpc

########################################################
################      TIMER       ######################
########################################################
- alias: Timer
  trigger:
  - platform: time
    seconds: 00
  condition:
  - condition: template
    value_template: '{{ now().strftime("%-H")|int == states.input_slider.timer_hour.state|int and now().strftime("%-M")|int == states.input_slider.timer_minute.state|int }}'
  action:
  - service: homeassistant.turn_on
    data_template:
      entity_id: >
        switch.{{states.input_select.timer_entity.state}}
  - delay: '{{states.input_slider.timer_length.state|int // 60 }}:{{ 0 if (((states.input_slider.timer_length.state|int)%60)|string)|length == 1 }}{{states.input_slider.timer_length.state|int % 60}}:00'
  - service: homeassistant.turn_off
    data_template:
      entity_id: >
        switch.{{states.input_select.timer_entity.state}}
  - service: automation.turn_off
    entity_id: automation.timer
  - condition: state
    entity_id: input_boolean.timer_repeat
    state: 'on'
  - service: automation.turn_on
    entity_id: automation.timer

- alias: Timer Default Off
  trigger:
  - platform: event
    event_type: homeassistant_start
  action:
  - service: automation.turn_off
    entity_id: automation.timer
  
    

########################################################
################ CHRISTMAS LIGHTS ######################
########################################################

#- alias: Turn on Christmas Outside Lights at sunrise
#  trigger:
#    platform: sun
#    event: sunrise
#    offset: "-01:00:00"
#  action:
#    - service: homeassistant.turn_on
#      entity_id: switch.wemo_switch_2
#- alias: Turn off Christmas Outside Lights at Morning
#  trigger:
#    platform: sun
#    event: sunrise
#    offset: "+00:20:00"
#  action:
#    - service: homeassistant.turn_off
#      entity_id: switch.wemo_switch_2
#- alias: Turn on Christmas Tree Lights at Morning
#  trigger:
#    platform: time
#    after: '07:30:00'
#  action:
#    - service: homeassistant.turn_on
#      entity_id: switch.wemo_switch_1
#- alias: Turn off Christmas Tree Lights at Morning
#  trigger:
#    platform: time
#    after: '09:30:00'
#  action:
#    - service: homeassistant.turn_off
#      entity_id: switch.wemo_switch_1
#- alias: Turn on Christmas Lights at Sunset
#  trigger:
#    platform: sun
#    event: sunset
#    offset: "-00:30:00"
#  action:
#    - service: homeassistant.turn_on
#      entity_id: switch.wemo_switch_1
#    - service: homeassistant.turn_on
#      entity_id: switch.wemo_switch_2
#- alias: Turn off Christmas Lights at Night
#  hide_entity: true
#  trigger:
#    platform: time
#    after: '23:00:00'
#  action:
#    - service: homeassistant.turn_off
#      entity_id: switch.wemo_switch_1
#    - service: homeassistant.turn_off
#      entity_id: switch.wemo_switch_2
