- platform: template
  sensors:
    home_occupancy:
      friendly_name: Home Occupancy
      entity_id:
      - binary_sensor.bigbee_occupancy
      - binary_sensor.lilbee_occupancy
      sensor_class: occupancy
      value_template: >-
        {%- if is_state("binary_sensor.bigbee_occupancy", "on")
            or is_state("binary_sensor.lilbee_occupancy", "on") -%}
          true
        {%- else -%}
          false
        {%- endif -%}

# Motion Sensors
- platform: mqtt
  name: Kitchen Table Motion
  state_topic: "home/downstairs/kitchen/table/motion"
  sensor_class: motion
- platform: mqtt
  name: Kitchen Cooking Area Motion
  state_topic: "home/downstairs/kitchen/cooking_area/motion"
  sensor_class: motion
- platform: mqtt
  name: Family Room Motion
  state_topic: "home/downstairs/family_room/motion"
  sensor_class: motion

# Door Sensors
- platform: mqtt
  name: Garage Door
  state_topic: "home/downstairs/garage/door"
  sensor_class: opening
  payload_on: "OPEN"
  payload_off: "CLOSED"
 
- platform: mqtt
  name: Inside Garage Door
  state_topic: "home/downstairs/garage/inside_door"
  sensor_class: opening
  payload_on: "OPEN"
  payload_off: "CLOSED"

