- platform: template
  sensors:
    home_occupancy:
      friendly_name: Home Occupancy
      entity_id:
      - binary_sensor.bigbee_occupancy
      - binary_sensor.lilbee_occupancy
      sensor_class: occupancy
      value_template: >-
        {%- if is_state("binary_sensor.bigbee_occupancy", "on")
            or is_state("binary_sensor.lilbee_occupancy", "on") -%}
          true
        {%- else -%}
          false
        {%- endif -%}

