#- platform: generic
#  name: Travel Time Map
#  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{states.sensor.center_travel_time_map_on.state}}&zoom={{states.input_number.travel_time_map_zoom.state|int+6}}&size=600x300&maptype=roadmap&markers=icon:https://hass.pinternet.us/local/male-icon.png|{{states.device_tracker["7ac50169"].attributes.latitude}},{{states.device_tracker["7ac50169"].attributes.longitude}}&markers=icon:https://hass.pinternet.us/local/female-icon.png|{{states.device_tracker.lgd801c8e9841a.attributes.latitude}},{{states.device_tracker.lgd801c8e9841a.attributes.longitude}}&key={{states.input_text.gcm_key.state}}
#  limit_refetch_to_url_change: true

- platform: generic
  name: Delta Mini
  still_image_url: !secret wyze_cam_1_url
  username: root
  password: !secret wyze_cam_1_passwd
  authentication: basic
  verify_ssl: false
  scan_interval: 5
#  limit_refetch_to_url_change: true