homeassistant:
  # Name of the location where Home Assistant is running
  name: home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 211
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  
  customize: !include customize.yaml
  whitelist_external_dirs:
    - '/home/hass/.homeassistant/www'
  
logger:
  default: warning
#  logs:
#    homeassistant.components.switch.mqtt: debug
#    homeassistant.components.hub.mqtt: debug
#    homeassistant.components.mqtt: debug

# Show links to resources in log and frontend
#introduction:

config:

# Enables the frontend
frontend:
  themes: !include themes.yaml

#http:
  # Uncomment this to add a password (recommended!)
#  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
#  base_url: !secret http_url
#  cors_allowed_origins:
#    - https://google.com
#  use_x_forwarded_for: True
#  ssl_certificate: !secret certificate
#  ssl_key: !secret key
  #ip_ban_enabled: True
  #login_attempts_threshold: 5

mqtt:
  broker: localhost

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
    - automation
    - group
    - camera
    - input_text
    - scene

# View all events in a logbook
#logbook:

recorder:
  purge_interval: 1
  purge_keep_days: 2
  exclude:
    domains:
      - camera
      - group
      - scene
    entities:
      - binary_sensor.kitchen_motion
      - binary_sensor.kitchen_table_motion
      - binary_sensor.living_room_motion
      - binary_sensor.dining_room_motion
      - input_text.gcm_key
      - sensor.center_travel_time_map_on

device_tracker:
  - platform: ddwrt
    host: 192.168.125.1
    username: !secret ddwrt_username
    password: !secret ddwrt_password
    track_new_devices: true
    hide_if_away: true
  - platform: ddwrt
    host: 192.168.125.3
    username: !secret ddwrt_username
    password: !secret ddwrt_password
    track_new_devices: true
    hide_if_away: true
  - platform: actiontec
    host: 192.168.3.1
    username: !secret actiontec_username
    password: !secret actiontec_password
    track_new_devices: true
    hide_if_away: true
  - platform: gpslogger
#  - platform: ddwrt
#    host: 192.168.125.4
#    username: !secret ddwrt_username
#    password: !secret ddwrt_password
#    track_new_devices: false
    

# Track the sun
#sun:

ecobee:
  api_key: !secret ecobee_key
  hold_temp: true

climate:
  platform: ecobee

wemo:
  static:
    - 192.168.125.20 #Plug-in Switch 1
    - 192.168.125.21 #Plug-in Switch 2
    - 192.168.125.22 #Front Porch
    - 192.168.125.23 #Dining Room

remote:
  - platform: harmony
    name: FamilyRoom
    host: 192.168.125.30

#media_player:
#  - platform: cast
    
#ifttt:
#  key: !secret ifttt_key

emulated_hue:
  type: alexa
  expose_by_default: true
  exposed_domains:
  - switch


# Text to speech
#tts:
#  platform: google

binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
cover: !include cover.yaml
group: !include groups.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
#input_slider: !include input_slider.yaml
#input_datetime: !include input_datetime.yaml
input_text: !include input_text.yaml
notify: !include notify.yaml
sensor: !include sensor.yaml
switch: !include switches.yaml
shell_command: !include shell_command.yaml

automation: !include automations.yaml
scene: !include scenes.yaml
script: !include script.yaml
alexa:
intent_script: !include alexa.yaml

map:
zone: !include zones.yaml

