- platform: darksky
  api_key: !secret darksky_key
  forecast:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  monitored_conditions:
  - temperature
  - wind_speed
  - temperature_high
  - temperature_low
  - apparent_temperature_high
  - apparent_temperature_low
  - precip_accumulation

#- platform: command_line
#  name: UPS Battery
#  command: 'sudo pwrstat -status | grep Battery | grep -o "[0-9]\{1,3\}"'
#  unit_of_measurement: "%"

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use_percent
      arg: /mnt/backup
    - type: disk_use_percent
      arg: /mnt/share
    - type: memory_use_percent
    - type: swap_use_percent
    - type: processor_use

#- platform: rest
#  name: Seth's Internal Location Data
#  scan_interval: 1
#  resource: !secret seths_internal_location
#  value_template: >
#    {% set key, value = (value_json.users.seth[0].rf|dictsort(false, "value")|last) %}
#    {{key}},{{value}},{{value_json.users.seth[0].time.split(".")[0]+"+0000"}}

- platform: template
  sensors:
    seths_cell_battery:
      friendly_name: "Seth's Cell Battery"
      unit_of_measurement: '%'
      icon_template: >-
        {% if is_state('binary_sensor.seths_cell_charging', 'on') %}
          mdi:battery-charging
        {% else %}
          mdi:battery
        {% endif %}
      value_template: >
        {{ states.device_tracker['7ac50169'].attributes.battery|int if states.device_tracker['7ac50169'].attributes.battery != none else 'unknown' }}
    christys_cell_battery:
      friendly_name: "Christy's Cell Battery"
      unit_of_measurement: '%'
      icon_template: >-
        {% if is_state('binary_sensor.christys_cell_charging', 'on') %}
          mdi:battery-charging
        {% else %}
          mdi:battery
        {% endif %}
      value_template: >
        {{ states.device_tracker.lgus9978cc74d43.attributes.battery|int if states.device_tracker.lgus9978cc74d43.attributes.battery != none else 'unknown' }}
#    seths_internal_location:
#      entity_id:
#      - sensor.seths_internal_location_data
#      value_template: >
#        {% set location, probability, time = (states.sensor.seths_internal_location_data.state.split( ",")) %}
#        {{location}}

#    seths_internal_location_text:
#      entity_id:
#      - sensor.seths_internal_location_data
#      value_template: >
#        {% set location, probability, time = (states.sensor.seths_internal_location_data.state.split( ",")) %}
#        There is a {{(float(probability)*100)|round(0)}}% chance Seth is at {{location}}. Last seen at {{as_timestamp(time)|timestamp_local}}
    
    family_room:
      value_template: >
        {{ states.remote.familyroom.attributes.current_activity if states.remote.familyroom != none else "PowerOff" }}

    indoor_temperature:
      friendly_name: Indoor Temperature
      unit_of_measurement: '°F'
      value_template: >-
        {{ states.climate.bigbee.attributes.current_temperature if states.climate.bigbee != none else NA}}
        
    tomorrows_forecast:
      friendly_name: Tomorrow
      value_template: >-
        {% if states.sensor.dark_sky_overnight_low_temperature_1d != none %}
          {{states.sensor.dark_sky_overnight_low_temperature_1d.state}} - {{states.sensor.dark_sky_daytime_high_temperature_1d.state}} {{states.sensor.dark_sky_daytime_high_temperature_1d.attributes.unit_of_measurement}}
        {% else %}
          NA
        {% endif %}

    center_travel_time_map_on:
      value_template: >-
        {% set center = states.input_select.center_travel_time_map_on.state %}
        {% if center == "Christy"%}
          {%set lat,lon = states.device_tracker.lgus9978cc74d43.attributes.latitude,states.device_tracker.lgus9978cc74d43.attributes.longitude%}
        {% elif center == "Seth" %}
          {% set lat,lon = states.device_tracker['7ac50169'].attributes.latitude,states.device_tracker['7ac50169'].attributes.longitude%}
        {% else %}
          {% set lat,lon = (states.device_tracker.lgus9978cc74d43.attributes.latitude + states.device_tracker['7ac50169'].attributes.latitude)/2.0, (states.device_tracker.lgus9978cc74d43.attributes.longitude + states.device_tracker['7ac50169'].attributes.longitude)/2.0%}
        {% endif %}
        {{ [lat,lon]|join(',') }}

      

- platform: deluge
  host: 127.0.0.1
  username: !secret deluge_user
  password: !secret deluge_password
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'

#- platform: google_travel_time
#  name: Travel Time Christy To Seth
#  api_key: !secret gcm_key
#  origin: device_tracker.lgus9978cc74d43
#  destination: device_tracker.7ac50169
#  update_interval: 180

#- platform: google_travel_time
#  name: Travel Time Seth To Christy
#  api_key: !secret gcm_key
#  origin: device_tracker.7ac50169
#  destination: device_tracker.lgus9978cc74d43
#  update_interval: 180

#- platform: google_travel_time
#  name: Travel Time Christy To Home
#  api_key: !secret gcm_key
#  origin: device_tracker.lgus9978cc74d43
#  destination: home
#  update_interval: 900

#- platform: google_travel_time
#  name: Travel Time Seth To Home
#  api_key: !secret gcm_key
#  origin: device_tracker.7ac50169
#  destination: home
#  update_interval: 900

- platform: mqtt
  name: Kitchen Sink Water Level
  state_topic: "home/downstairs/kitchen/sink/water_level"
- platform: mqtt
  name: Kitchen Dishwasher Water Level
  state_topic: "home/downstairs/kitchen/dishwasher/water_level"
- platform: mqtt
  name: Kitchen Fridge Water Level
  state_topic: "home/downstairs/kitchen/fridge/water_level"
- platform: mqtt
  name: Basement Sump Water Level
  state_topic: "home/basement/sump/water_level"
  availability_topic: "home/esp8266BasementSensors/availability"
- platform: mqtt
  name: Basement Water Heater Water Level
  state_topic: "home/basement/water_heater/water_level"
- platform: mqtt
  name: Washer Water Level
  state_topic: "home/basement/washer/water_level"
- platform: mqtt
  name: Kitchen Light Level
  state_topic: "home/downstairs/kitchen/lux"
- platform: mqtt
  name: Living Room Light Level
  state_topic: "home/downstairs/living_room/light_level"
- platform: mqtt
  name: Christmas Tree Water Level
  state_topic: "home/downstairs/christmas_tree/water_level"
